/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cobhopfnjktuwpxkejlz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYmhvcGZuamt0dXdweGtlamx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNDExNjEsImV4cCI6MjA4MjkxNzE2MX0.A8-5E_aqi83yR5P21gFMxfm-TU1QdGUqBNVqWHIHvRQ"